project:
  type: website
  output-dir: docs

lang: de-CH  # Behält de-CH für HTML und PDF bei 
number-sections: true

format:
  html:
    theme: cosmo
    toc: true
    code-fold: false
  pdf:
    pdf-engine: lualatex
    classoption: ngerman  # <-- Diese Zeile hinzufügen
    toc: false
    output-file: zotero_anleitung.pdf
    template-partials:
      - title.tex
    geometry:
      - left=4cm
      - right=4cm