---
title: "Zotero"
subtitle: "Einführung für Lehrpersonen"
#author: "Dein Name"
date: 2026-01-28
date-format: "DD.MM.YYYY"
---

Zotero bewirbt sich selber als persönlicher Forschungsassistent. Im
gymnasialen Umfeld ist Zotero in erster Linie ein Hilfsmittel Zitate in
Texten korrekt zu formatieren. Darüber hinaus kann Zotero auch als
E-Reader mit Zusatzfunktionen zur Verwaltung von Notizen verwendet
werden. 

Diese Anleitung zeigt Schritt für Schritt wie

* Zotero installiert wird;
* Einträge in die Zotero Bibliothek gemacht werden können;
* Referenzen in einen Text aufgenommen werden, sowie
* Zotero als Wissensdatenbank verwendet werden kann.

## Zotero installieren und einrichten

Um die Funktionen von Zotero im vollen Umfang zu nutzen, ist es sinnvoll
ein Zotero Account zu erstellen. Der Account kann auf der Website von
[Zotero](https://www.zotero.org/user/register) erstellt werden. Wenn der
Account nicht ausschliesslich privat genutzt werden soll, ist es
sinnvoll die Schul- bzw.\ Geschäftsemail zu verwenden. Im Nutzerprofil
können auch mehrere Adressen hinterlegt werden. Das ermöglicht es, die
eigene Datenbank zu behalten, wenn man eine Institution verlässt.

Nachdem optional ein persönlicher Account erstellt worden ist, kann der
[Zotero Desktop Client](https://www.zotero.org/download/)
heruntergeladen und installiert werden. Auf der gleichen Seite findet
sich auch die Möglichkeit den Zotero Connector als Browser Plugin
herunterzuladen. Dieses Plugin ist für die Arbeit mit Zotero nicht
zwingend erforderlich, vereinfacht aber die Erfassung von Quellen
ungemein.

Wenn Zotero installiert ist, kann es über den Menüpunkt Bearbeiten >
Einstellungen, Registerkarte Sync mit dem eigenen Zotero Account
verbunden werden.

## Einträge in Zotero erstellen und organisieren

Es gibt verschiedene Methoden, wie Einträge in die Zotero Bibliothek
aufgenommen werden können. Hier werden die gängigen Methoden Schritt für
Schritt mit Beispielen erklärt.

* Eintrag mit dem Zotero Connector erfassen.
  
  Damit Einträge mit dem Zotero Connector erfasst werden können, muss
  neben dem Browser auch die Zotero Desktop Applikation geöffnet sein.
  Gearbeitet wird bei geöffneter Zotero Desktop Applikation im Browser.

  Nach der Installation des Zotero Connectors für den verwendeten
  Browser muss dieser via Plugin Manager (in den meisten Browser ein
  Icon, das wie ein Puzzle Teil aussieht) an die Menüzeile angepinnt
  werden. Durch das Anpinnen erscheint in der Menüzeile ein neues Symbol
  in Form eines grauen Buchstaben 'Z'.

  Für das Beispiel soll der [Wikipedia Artikel zu
  Zotero](https://de.wikipedia.org/wiki/Zotero) erfasst werden. Dazu
  muss die [Website](https://de.wikipedia.org/wiki/Zotero) geöffnet
  werden. Wenn die Website offen ist, kann das graue 'Z' Symbol
  angeklickt werden. Beim erstmaligen Anklicken erscheint ein
  Hinweisfenster. Dieses kann angenommen werden. Anschliessend öffnet
  sich oben rechts im Browser ein Pop-Up Fenster, das einem Mitteilt,
  dass die Website nach Zotero gespeichert wird und dass ein Snapshot
  der Website angelegt wird. Ausserdem hat das Symbol für den Zotero
  Connector eine neue Darstellung erhalten. Neu sieht es wie ein
  aufgeschlagenes Buch aus. So zeigt der Zotero Connector an, als welche
  Kategorie der Eintrag angelegt wird. Im Fall der Wikipedia ist das ein
  Enzyklopädieartikel. Der Zotero Connector erkennt mehr oder weniger
  zuverlässig, um was für einen Eintrag es sich handelt. Der Eintrag
  muss aber in jedem Fall kontrolliert und gegebenenfalls ergänzt und
  korrigiert werden.

  Ebenfalls über den Zotero Connector können bibliographische Angaben
  aus Bibliothekskatalogen übernommen werden. Als Beispiel dient hier ein
  Eintrag im swisscovery Katalog zu 
  [Le rouge et le
  noir](https://swisscovery.slsp.ch/discovery/fulldisplay?docid=alma991171274013205501&context=L&vid=41SLSP_NETWORK:VU1_UNION&lang=de&search_scope=DN_and_CI&adaptor=Local%20Search%20Engine&isFrbr=true&tab=41SLSP_NETWORK&query=any,contains,le%20rouge%20et%20le%20noir&sortby=date_d&facet=frbrgroupid,include,9034117119244122733&offset=0).
  Wenn dieser Eintrag aufgerufen wird, nimmt der Zotero Connector die
  Form eines Buches an. Dieser Eintrag wird als Buch angelegt,
  allerdings ohne Snapshot. Der Zotero Connector erkennt korrekt, dass
  die Website von swisscovery ausschliesslich die Metadaten zum Buch zur
  Verfügung stellt.

  Andere Websites funktionieren analog zu diesen beiden Beispielen.

* Eintrag mittels eines Identifikators erfassen.
  
  In der Zotero Desktop Applikation können Einträge mittels der ISBN,
  DOI und ähnlicher Identifikatoren erfasst werden. Dazu ist das
  Zauberstab Icon über der Liste mit den Einträgen anzuklicken. Im sich
  öffnenden Fenster kann die ISBN eingegeben werden. Zotero sucht mit
  der ISBN online nach Einträgen mit der entsprechenden ISBN in
  Bibliothekskatalogen.  
  Als Beispiel dient hier die ISBN 9783110466201, Ovid, Niklas Holzberg (Hrsg.),
  Metamorphosen lateinisch-deutsch. Sammlung Tusculum. De Gruyter, 2017.

  Auch die via ISBN erfassten Einträge müssen unbedingt auf
  Vollständigkeit und Korrektheit kontrolliert werden.

* Manueller Eintrag.
  
  Es besteht auch die Möglichkeit, Einträge komplett manuell zu
  erfassen. Dazu ist das Icon links neben dem Zauberstab (leeres Blatt
  mit kleinem Plus Symbol) zu verwenden. Wenn dieses Icon angeklickt
  wird, öffnet sich ein Auswahlmenü mit allen Eintragsarten, welche von
  Zotero zur Verfügung gestellt werden. Sobald eine Wahl getroffen
  worden ist, wird ein leerer Eintrag in der gewählten Kategorie
  angelegt. Die entsprechenden Metadaten können nun von Hand eingegeben
  werden. 

Eine ausführliche Anleitung, wie Einträge in Zotero erfasst werden, wird
auf der [Website von
Zotero](https://www.zotero.org/support/adding_items_to_zotero) zur
Verfügung gestellt. 

Zotero stellt zwei Möglichkeiten zur Verfügung, die Bibliothek zu
organisieren. Die Einträge können in Sammlungen organisiert werden oder
mit Tags versehen werden. Beide Möglichkeiten können parallel verwendet
werden.

Zotero Sammlungen werden mit einem ähnlichen Icon dargestellt wie
Windows Ordner. Dies darf aber nicht über einen grundsätzlichen
Unterschied hinwegtäuschen. Während Dateien in Windows Ordnern
ausschliesslich in einem Ordner gespeichert sind, stellen Zotero
Sammlungen keine Speicherorte dar. Das heisst, Zotero Einträge können in
mehreren Sammlungen gleichzeitig zusammengefasst werden.

Neue Sammlungen oder Untersammlungen werden durch einen Rechtsklick auf
'Meine Sammlung' oder eine bereits bestehende Sammlung angelegt. Im sich
öffnenden Kontextmenü kann dann der Eintrag 'Neue Sammlung' bzw. 'Neue
Untersammlung' ausgewählt werden.

Um einen Eintrag mit einem Tag zu versehen, muss dieser in der
Bibliothek ausgewählt werden. Ganz am rechten Rand erscheint dann eine
Auswahl mit mehreren farbigen Icons. Um ein Tag zu vergeben, ist das
Icon, welches wie eine Gepäcketikette aussieht auszuwählen.

Eine ausführliche Beschreibung für die 
[Organisation](https://www.zotero.org/support/collections_and_tags)
einer Zotero Bibliothek findet sich ebenfalls auf der Website von
Zotero. 
